### ISSUE TITLE
Bug Report | 

### ISSUE THREAD

**Issue by DrakMC** [Clientastisch/Cardinal-Anticheat#123] opened 2020-07-03 21:21 UTC
What type of bug you want to report? Describe it here
I get this error randomly in the Cardinal AntiCheat log.

When the bug occurrs?
Randomly

Cardinal Version: 0.9992

Spigot Version: Paper Spigot 1.8.8

> **Attached Files  (Required)**
https://pastebin.com/t8c9FFRB

**Comment by Clientastisch** [comment] 2020-07-03 21:41
This **should** be fixed in the next update.
However because you couldn't tell me a way to reproduce that I can't say so for sure

**Closed by Clientastisch** 2020-07-03 21:41 UTC
Labels: Bug Report
